# Generated by Django 5.0.1 on 2025-02-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
